# Logistic Regression Implementation

In [261]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
%matplotlib inline

In [262]:
# for cretating classification datasets
from sklearn.datasets import make_classification



In [263]:
# Create Dataset 
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=8)
# X independent 
# y dependent 
# n_ smaple 1000 data points 
# classes -> 2 for binary classification 



In [264]:
X

array([[-0.49317802, -0.88011788,  1.17773615, ..., -0.98712265,
        -0.99402129, -0.81999775],
       [-1.03439597,  1.23321442, -0.6018178 , ..., -0.95339576,
        -0.80576554, -0.92878681],
       [ 0.58183629,  1.17457336,  1.13990086, ...,  1.82884458,
         0.16722037,  1.80062741],
       ...,
       [-0.36697299,  0.15793381, -1.89063906, ...,  0.54957702,
        -1.25951878,  0.185343  ],
       [-0.13313836,  0.72201597,  1.25378722, ..., -2.04860096,
        -0.12496322, -2.20431958],
       [ 1.93445693,  1.87870334,  1.68894786, ..., -0.81745002,
        -1.64852134, -0.98345898]])

In [265]:
pd.DataFrame(X) # TO see our independent features in table form

0         1         2         3         4         5         6  \
0   -0.493178 -0.880118  1.177736 -0.580361  0.150037  1.052141 -0.360442   
1   -1.034396  1.233214 -0.601818  0.020624  0.322365  0.686073 -0.227435   
2    0.581836  1.174573  1.139901 -0.120227 -0.817239 -1.270234 -0.796728   
3    0.954871 -1.196242 -0.499768  1.603601  0.014108 -1.811135 -0.544676   
4   -0.802371 -0.208252  0.754947 -1.821381 -1.273454  1.832946  1.648218   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.403679  0.093320 -0.261457  0.710879 -1.013009 -0.104215  0.709576   
996  0.683783  1.603757  0.452889  1.453379 -0.949077  0.447241 -0.402589   
997 -0.366973  0.157934 -1.890639  1.475129  0.642057 -1.240166  0.969343   
998 -0.133138  0.722016  1.253787  0.930443 -0.630286  0.970839 -1.480410   
999  1.934457  1.878703  1.688948  0.812529  1.244778  0.136742 -0.884988   

            7         8         9  
0   -0.987123 -0.994021 -0.819998  
1   -0.953396 -0.805766 -0.928787  
2    1.828845  0.167220  1.800627  
3    1.229989 -0.985845  0.814485  
4   -1.090767  1.496966 -0.628300  
..        ...       ...       ...  
995 -0.409335 -1.017561 -0.564028  
996 -1.739064  0.851077 -2.027450  
997  0.549577 -1.259519  0.185343  
998 -2.048601 -0.124963 -2.204320  
999 -0.817450 -1.648521 -0.983459  

[1000 rows x 10 columns]

In [266]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)


In [267]:
X_train.shape

(700, 10)

In [268]:
# MODEL TRAINING 
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

In [269]:
logistic.fit(X_train,y_train)


LogisticRegression()

In [270]:
y_pred=logistic.predict(X_test)
print(y_pred)

[1 0 1 1 0 0 0 0 0 1 0 1 0 1 1 1 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 0 0 0 0
 1 1 1 1 1 1 0 0 1 0 0 1 1 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1
 0 1 0 1 0 1 0 1 1 0 0 0 0 1 1 0 1 1 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0
 1 1 0 0 0 1 1 1 0 1 1 1 0 0 0 0 1 1 1 0 0 1 0 0 1 0 1 0 0 1 1 1 0 0 0 1 1
 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 1 0
 0 1 1 1 0 1 0 0 0 0 0 1 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 1 0 0 0 1 0 0 1 0 0
 1 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 1 1 1 1 1 1 1 0 0 0
 0 0 0 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1
 0 0 1 1]


In [271]:
# logistic.predict_proba(X_test) for probaility 

In [272]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report




In [273]:
score=accuracy_score(y_test,y_pred)
print("accuracy_score",score)
cm=confusion_matrix(y_test,y_pred)
print("confusion Matrix: \n",cm)
print(classification_report(y_test,y_pred))

accuracy_score 0.91
confusion Matrix: 
 [[134   9]
 [ 18 139]]
              precision    recall  f1-score   support

           0       0.88      0.94      0.91       143
           1       0.94      0.89      0.91       157

    accuracy                           0.91       300
   macro avg       0.91      0.91      0.91       300
weighted avg       0.91      0.91      0.91       300



## Hyperparameter Tuning and Cross Validation 
 

## Grid Search CV - takes all combination 

In [274]:
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg', 'lbfgs','liblinear', 'sag', 'saga'] 

In [275]:
params=dict(penalty=penalty,C=c_values ,solver=solver)

In [276]:
# GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold() # in this cv each fold has a balance propertiesb of each 
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

# estimator = model 
# param_grid = params 
# n_jobs=-1 uses all cpu cores to spped up 

In [277]:
grid


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [278]:
grid.fit(X_train,y_train)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [279]:
grid.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'liblinear'}

In [280]:
grid.best_score_

0.9

In [281]:
y_pred=grid.predict(X_test)  

In [282]:
score=accuracy_score(y_pred,y_test)
print("accuracy_score",score)
cm=confusion_matrix(y_pred,y_test)
print("confusion Matrix: \n",cm)
print(classification_report(y_pred,y_test))

accuracy_score 0.8833333333333333
confusion Matrix: 
 [[134  26]
 [  9 131]]
              precision    recall  f1-score   support

           0       0.94      0.84      0.88       160
           1       0.83      0.94      0.88       140

    accuracy                           0.88       300
   macro avg       0.89      0.89      0.88       300
weighted avg       0.89      0.88      0.88       300



## Randomised Search CV 
- takes Random attributes/parameters 

In [283]:
from sklearn.model_selection import RandomizedSearchCV
model=LogisticRegression()
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring='accuracy')


In [284]:
randomcv.fit(X_train,y_train)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
40 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py", line 1203, in fit
    raise 

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [285]:
randomcv.best_score_

0.8914285714285715

In [286]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 0.1}

In [287]:
y_pred=randomcv.predict(X_test)

In [288]:
score=accuracy_score(y_pred,y_test)
print("accuracy_score",score)
cm=confusion_matrix(y_pred,y_test)
print("confusion Matrix: \n",cm)
print(classification_report(y_pred,y_test))

accuracy_score 0.9133333333333333
confusion Matrix: 
 [[134  17]
 [  9 140]]
              precision    recall  f1-score   support

           0       0.94      0.89      0.91       151
           1       0.89      0.94      0.92       149

    accuracy                           0.91       300
   macro avg       0.91      0.91      0.91       300
weighted avg       0.91      0.91      0.91       300



## Logistic Regression for Multi Class Classifcation 

In [289]:
X,y=make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=15)

In [290]:
y

array([2, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 2,
       2, 1, 1, 0, 2, 0, 2, 1, 2, 1, 2, 2, 0, 1, 2, 1, 1, 2, 1, 1, 2, 2,
       0, 2, 1, 0, 2, 0, 0, 1, 0, 1, 1, 0, 2, 2, 0, 1, 1, 2, 0, 0, 1, 0,
       0, 1, 2, 2, 0, 1, 2, 2, 1, 2, 0, 2, 0, 0, 1, 0, 2, 0, 2, 0, 0, 2,
       1, 2, 0, 0, 2, 0, 1, 0, 2, 0, 2, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 0,
       1, 0, 1, 2, 1, 1, 1, 2, 0, 2, 0, 2, 1, 1, 0, 0, 1, 1, 2, 2, 1, 2,
       0, 1, 2, 2, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1, 2, 0, 2, 1, 1, 0, 2, 1,
       0, 2, 2, 2, 2, 2, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       2, 2, 1, 2, 2, 2, 2, 0, 1, 0, 1, 0, 2, 2, 2, 1, 1, 0, 0, 0, 2, 0,
       0, 0, 1, 0, 2, 1, 0, 2, 2, 1, 1, 1, 1, 2, 0, 1, 2, 2, 1, 1, 0, 2,
       2, 1, 0, 2, 2, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 2, 0, 0, 0, 0, 2, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 2, 1, 0, 1, 1, 2, 2, 2, 2, 0, 1, 0,
       0, 2, 2, 1, 2, 0, 0, 1, 1, 2, 2, 1, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0,
       2, 0, 1, 0, 0, 2, 2, 1, 0, 2, 0, 1, 2, 2, 2,

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.30,random_state=42)


In [292]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression(multi_class='ovr')
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)


/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [293]:
y_pred

array([2, 1, 2, 1, 1, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2, 1,
       1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 1, 2, 0, 0, 2, 2, 1, 2, 2, 2, 1,
       2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       2, 1, 0, 1, 0, 1, 2, 1, 2, 2, 1, 0, 1, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       2, 1, 1, 2, 2, 0, 0, 0, 2, 2, 0, 1, 2, 1, 2, 1, 0, 2, 0, 2, 0, 1,
       2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 2, 0, 1, 2, 0, 0, 2, 2, 2, 1, 2, 0,
       2, 2, 0, 0, 0, 2, 0, 2, 0, 1, 2, 1, 1, 2, 0, 0, 1, 1, 2, 2, 2, 1,
       2, 0, 2, 2, 2, 1, 0, 2, 0, 0, 2, 0, 2, 0, 0, 1, 2, 0, 1, 1, 1, 1,
       0, 2, 1, 0, 0, 1, 2, 2, 2, 2, 2, 0, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1,
       0, 0, 1, 2, 2, 0, 0, 2, 1, 2, 1, 0, 0, 2, 1, 1, 1, 2, 2, 1, 2, 1,
       0, 1, 0, 0, 1, 0, 2, 1, 0, 2, 2, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 1, 2, 2, 2, 1, 0, 0, 1, 0, 2,
       1, 2, 0, 0, 0, 2, 2, 1, 2, 0, 1, 1, 0, 0, 0, 1, 0, 2, 2, 0, 2, 0,
       0, 0, 1, 1, 2, 0, 1, 2, 2, 0, 1, 2, 0, 2])

In [294]:
score=accuracy_score(y_pred,y_test)
print("accuracy_score",score)
cm=confusion_matrix(y_pred,y_test)
print("confusion Matrix: \n",cm)
print(classification_report(y_pred,y_test))

accuracy_score 0.79
confusion Matrix: 
 [[84  3 10]
 [10 74  7]
 [ 8 25 79]]
              precision    recall  f1-score   support

           0       0.82      0.87      0.84        97
           1       0.73      0.81      0.77        91
           2       0.82      0.71      0.76       112

    accuracy                           0.79       300
   macro avg       0.79      0.79      0.79       300
weighted avg       0.79      0.79      0.79       300



## Hyperparameter Tunning 

In [295]:
# Grid Search CV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold


model=LogisticRegression()
param_grid =["l1","l2","elasticnet"]
c_values=[100,10,1,0.1,0.01]
solver=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
params=dict(penalty=penalty,C=c_values ,solver=solver)

cv=StratifiedKFold()
grid=GridSearchCV(estimator=model,param_grid=params,scoring="accuracy",cv=cv,n_jobs=-1)

In [296]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [297]:
grid.fit(X_train,y_train)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [298]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}

In [299]:
grid.best_score_

0.8042857142857143

In [300]:
y_pred=grid.predict(X_test)

In [301]:
score=accuracy_score(y_pred,y_test)
print("accuracy_score",score)
cm=confusion_matrix(y_pred,y_test)
print("confusion Matrix: \n",cm)
print(classification_report(y_pred,y_test))

accuracy_score 0.7733333333333333
confusion Matrix: 
 [[84  4  8]
 [11 74 14]
 [ 7 24 74]]
              precision    recall  f1-score   support

           0       0.82      0.88      0.85        96
           1       0.73      0.75      0.74        99
           2       0.77      0.70      0.74       105

    accuracy                           0.77       300
   macro avg       0.77      0.78      0.77       300
weighted avg       0.77      0.77      0.77       300



## Random Search CV


In [302]:
from sklearn.model_selection import RandomizedSearchCV 
model=LogisticRegression()
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring='accuracy')
randomcv.fit(X_train,y_train)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
20 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver 

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [303]:
randomcv.best_score_

0.8042857142857143

In [304]:
randomcv.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.1}

In [305]:
y_pred=randomcv.predict(X_test)

In [306]:
score=accuracy_score(y_pred,y_test)
print("accuracy_score",score)
cm=confusion_matrix(y_pred,y_test)
print("confusion Matrix: \n",cm)
print(classification_report(y_pred,y_test))

accuracy_score 0.7833333333333333
confusion Matrix: 
 [[85  3 10]
 [ 9 76 12]
 [ 8 23 74]]
              precision    recall  f1-score   support

           0       0.83      0.87      0.85        98
           1       0.75      0.78      0.76        97
           2       0.77      0.70      0.74       105

    accuracy                           0.78       300
   macro avg       0.78      0.79      0.78       300
weighted avg       0.78      0.78      0.78       300

